### DISCUSSION TITLE
How to change caption line height?

### DISCUSSION THREAD

**Discussion by thaidev247** [sampotts/plyr#2694] [Q&A]
I tried to use
```css
.plyr__captions {
  line-height: 1.0;
}
```
but not working...
