### ISSUE TITLE
[New feature] Add browser fullscreen feature for desktop

### ISSUE THREAD

**Issue by kfeng0806** [sampotts/plyr#1068]
![](https://i.imgur.com/2CNxSal.jpg)
It would be nice if video player has ability to make fullscreen only inside the desktop browser.
User can still fluent switching between tabs without exit the "real fullscreen".

**Comment by sampotts** [comment]
I'm assuming you mean a sort of "full window"?

**Comment by kfeng0806** [comment]
@sampotts 
Exactly, video play on the top of full window size but not into fullscreen.

**Comment by friday** [comment]
So basically toggling a class with something like this?

```css
.pseudo-fullscreen {
  position: fixed !important;
  margin: 0 !important;
  top: 0 !important;
  right: 0 !important;
  bottom: 0 !important;
  left: 0 !important;
  z-index: 99999 !important;
}
```

I've been thinking about something like that for ios support, but don't personally see much utility in having multiple options for desktop.
