### ISSUE TITLE
How can i set control options dynamically like ['play', 'progress', 'current-time']?

### ISSUE THREAD

**Issue by sonupandit** [sampotts/plyr#1594]
Actually i want only large play button when video is paused. and bottom controls when video start playing.

**Comment by kfeng0806** [comment]
you can do that by adding custom css to control class

**Comment by Daaaaad** [comment]
@kfeng0806 Can you give us an example?

I would like to be able to edit player controls on play...

player.config.controls = ['play-large'] is not working :(

**Comment by kfeng0806** [comment]
@Daaaaad Can you explain more specific what you want?

If you like to make some layout change inside player base on play state you can do that by adding css like

```scss
// Media is playing
.plyr--playing {
    // Some element inside player container
    .plyr__controls {
        display: none;
    }
}
// Media is paused
.plyr--paused {
   // Some element inside player container
   .plyr__controls {
        display: block;
    }
}
```
