### ISSUE TITLE
Border/corner radius for audio player

### ISSUE THREAD

**Issue by epignosis567** [sampotts/plyr#1845]
Hi. I can't find anything in the documentation about adjusting the corner radius of the audio player. The Slack link doesn't work and I can't find any other support options.

**Comment by araynimax** [comment]
Just use a wrapper with the desired css: https://codepen.io/araynimax/pen/mdVJPYX

**Comment by araynimax** [comment]
You should just take a look into the generated html and use css afterwards: https://codepen.io/araynimax/pen/mdVJPYX

**Comment by vincentorback** [comment]
And take a look at the pseudo elements. Here are some examples and you will want to prefix these `::` properties.

```css
.plyr__progress__buffer::progress-bar,
.plyr--full-ui input[type="range"]::range-track,
.plyr--full-ui input[type="range"]::range-thumb,
.plyr--full-ui input[type="range"]::range-progress {
  border-radius: 0;
}
```
