### ISSUE TITLE
Open options dropdown down if there's no space above

### ISSUE THREAD

**Issue by nepomuc** [sampotts/plyr#1852]
I created a sticky container with plyr inside. When it gets sticked to the top of the page and the user wants to open the options dropdown it still open to the top:

![image](https://user-images.githubusercontent.com/864660/83016396-29de7b00-a022-11ea-91a0-c6099a08f511.png)

I would love to see a simple solution where I can set the opening-direction of the options dropdown or a more clever solution where the dropdown decides based on available space, like known from Bootstrap's tooltips for example.

**Comment by garbinmarcelo** [comment]
@nepomuc Did you find any solution for this?

**Comment by nepomuc** [comment]
@garbinmarcelo Nope, but I created a workaround for the time until plyr will have this feature built in. Since I'm using https://github.com/rgalus/sticky-js I use it's "data-sticky-class" attribute, which adds a class to the sticked element. Example: https://github.com/rgalus/sticky-js#examples

In my case this class is called "nm-sticky--sticked". So I added some new CSS to relocate the plyr settings popup below the settings icon:

```css
.nm-sticky--sticked .plyr .plyr__menu__container {
  bottom: auto;
  top: 100%;
  margin-bottom: 0;
  margin-top: 10px;
}
.nm-sticky--sticked .plyr .plyr__menu__container:after {
  display: none;
}
```

Live example @ https://nepomuc.com/qualifikationen/#h2-lebenslauf when you click on the button "Audio-Guide starten".
