### ISSUE TITLE
[Audio] Download button color does not change with color parameter

### ISSUE THREAD

**Issue by EsterfanoLopes** [sampotts/plyr#1946]
### Expected behaviour
Expecting to `--plyr-audio-control-color` parameter change all button colors for áudio.

### Actual behaviour
That i noticed, only the download button does not change its color with this parameter.

### Steps to reproduce
Using this object to render.
```css
.player-container{
    margin: 30px auto;
    height: fit-content;
    box-shadow: 0 0 10px rgba(254,117,25,1);
    font-family: 'Open Sans', sans-serif;
    --plyr-color-main: #FE7519;
    --plyr-menu-item-arrow-color: #FE7519;
    --plyr-audio-progress-buffered-background:rgba(254,117,25,0.3);
    --plyr-audio-controls-background: #000;
    --plyr-audio-control-color: #FE7519;
    --plyr-video-control-color: #FE7519;
}
```

![image](https://user-images.githubusercontent.com/15802819/92189349-ce980200-ee34-11ea-9918-f48a0ea79976.png)
Hover:
![image](https://user-images.githubusercontent.com/15802819/92189365-d788d380-ee34-11ea-9114-b6a2a4e1806e.png)

### Environment

- Browser: Chrome
- Version: 85.0.4183.83
- Operating System: Windows
- Version: Windows 10 PRO

Could'nt reproduce on https://codepen.io/pen?template=rKLywR
