### ISSUE TITLE
Getting `object-fit: cover` on Youtube videos

### ISSUE THREAD

**Issue by yousefamar** [sampotts/plyr#2425]
This isn't quite a bug report or feature request as much as it is asking for advice.

It's straightforward to stretch HTML5 videos to remove letterboxing, but is there a way to do this for Youtube videos?

This is especially problematic on mobile screens, as 3/4 of the screen is taken up by letterboxing for our app.

See minimal example here: https://codepen.io/Paraknight/pen/LYOeQqM

**Comment by yousefamar** [comment]
I think I found a solution (combined with getting rid of the YouTube elements:

```css
.plyr iframe[id^="youtube"] {
  top: -50%;
  height: 200%;
  width: 100%;
}
@media (max-aspect-ratio: 16/9) {
  .plyr iframe[id^="youtube"] {
    width: 177.7777vh;
    left: calc(0.5 * (100% - 177.7777vh));
  }
}
```
