### ISSUE TITLE
Simple way to change the color?

### ISSUE THREAD

**Issue by weavermedia** [sampotts/plyr#662]
This is not a bug. Just a question about the simplest way to change the blue color used on Plyr UI elements.

I'm loading the CSS and JS from CDN and using the simplest `plyr.setup();` script.

It would be great to be able to pass a custom color in the `setup` call which changed all the UI blue colors to custom.

Any way to do this?

**Comment by sampotts** [comment]
Nope - the styling is taken care of with the LESS/CSS so you'd need to build and host your own. Later on once CSS variables are becoming more mainstream then it'd be possible to do using those. I'd prefer to keep the styling in CSS and the JS handling logic as they were designed to do.

**Comment by weavermedia** [comment]
Gotcha, makes sense 👍 

Is there a CSS 'cheat sheet' that shows the selectors to target for coloring the play button and progress bars and hover states?

**Comment by sampotts** [comment]
It would be a case of editing this hex color:
https://github.com/sampotts/plyr/blob/master/src/less/variables.less#L12

..then you can build the CSS by first running `npm install` in the root of the project to install the dependencies and then run `gulp` which will output the CSS to `dist/plyr.css` . If you don't have NPM then you'll need to install node - you can use homebrew for this on a mac or just install the package on Windows.

**Comment by weavermedia** [comment]
Thanks. Is it not practical to do when using direct CDN sources? I targeted a couple of the UI elements but couldn't figure out the progress bar.

**Comment by sampotts** [comment]
Nope - the CDN is the processed LESS so you'll need to host it yourself. Eventually once CSS variables get more support then it'll be possible.

**Comment by Hi1307** [comment]
Sorry to reopen, but is there any update on this? The referenced file no longer exists and in that time CSS Variables has gained [wider browser support](https://caniuse.com/#feat=css-variables).

**Comment by RCD-Y** [comment]
@Hi1307 If you're still interested in this topic, I think adding `filter: hue-rotate(...deg)` to the control div would be a quick and easy hack to change the color for now.

**Comment by orangcrsh** [comment]
> @Hi1307 If you're still interested in this topic, I think adding `filter: hue-rotate(...deg)` to the control div would be a quick and easy hack to change the color for now.

I tried this lol look : 

`<div class="plyr__video-embed" id="player" style="max-width:640px; max-height:360px; filter: hue-rotate(180deg);">
        <iframe
            src="https://www.youtube.com/watch?v=hL-BvWLPseE?origin=https://plyr.io&amp;iv_load_policy=3&amp;modestbranding=1&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;enablejsapi=1"
            allowfullscreen
            allowtransparency
            allow="autoplay"
        ></iframe>
    </div>`

But the Hue of the video also is changing any way of how to fix this ?

**Comment by Malthehave** [comment]
I'm having the same issue.

**Comment by trych** [comment]
Me too. Would love to have a simpler way of changing the main color.

**Comment by Moeefa** [comment]
You can change the player color using this code:
```css
.plyr--full-ui input[type=range] {
  color: YourColor;
}

.plyr__control--overlaid {
  background: rgba(YourRGBColor, .5);
}

.plyr--video .plyr__control.plyr__tab-focus,
.plyr--video .plyr__control:hover,
.plyr--video .plyr__control[aria-expanded=true] {
  background: YourColor;
}

.plyr__control.plyr__tab-focus {
  box-shadow: 0 0 0 5px rgba(YourRGBColor, .5);
}

.plyr__menu__container .plyr__control[role=menuitemradio][aria-checked=true]::before {
  background: YourColor;
}
```
I hope I helped you!

**Comment by th-santos** [comment]
> 
> 
> You can change the player color using this code:
> 
> ```css
> .plyr--full-ui input[type=range] {
>   color: YourColor;
> }
> 
> .plyr__control--overlaid {
>   background: rgba(YourRGBColor, .5);
> }
> 
> .plyr--video .plyr__control.plyr__tab-focus,
> .plyr--video .plyr__control:hover,
> .plyr--video .plyr__control[aria-expanded=true] {
>   background: YourColor;
> }
> 
> .plyr__control.plyr__tab-focus {
>   box-shadow: 0 0 0 5px rgba(YourRGBColor, .5);
> }
> 
> .plyr__menu__container .plyr__control[role=menuitemradio][aria-checked=true]::before {
>   background: YourColor;
> }
> ```
> 
> I hope I helped you!

Perfect! Thanks.

**Comment by zakickes** [comment]
Having trouble getting this to work. My players are set up as follows.

**html**
`<div class="filterDiv sound show vid" id="none" name="In The Rat Cave With">
            <div class="js-player" data-plyr-provider="youtube" data-plyr-embed-id="Vc9Jwt7WtBE"></div></div>`

**script**
`const players = Array.from(document.querySelectorAll('.js-player')).map(p => new Plyr(p));`

I've tried copying the css as is using .plyr, and have replaced .plyr with my class .js-player, with no results. I'm attempting to change to color of the play/pause button and the volume slider (blue be default)

**Comment by Moeefa** [comment]
@zakickes I think you can have different colors for different videos using something like sass or javascript.
Example:
```js
document.getElementById("MyElement").style.color = "#"+((1<<24)*Math.random()|0).toString(16);
```

**Comment by bveenhof** [comment]
@zakickes I have the same problem; styling is not applied. How did you fix it?

**Comment by daymien** [comment]
> You can change the player color using this code:
> 
> ```css
> .plyr--full-ui input[type=range] {
>   color: YourColor;
> }
> 
> .plyr__control--overlaid {
>   background: rgba(YourRGBColor, .8);
> }
> 
> .plyr--video .plyr__control.plyr__tab-focus,
> .plyr--video .plyr__control:hover,
> .plyr--video .plyr__control[aria-expanded=true] {
>   background: YourColor;
> }
> 
> .plyr__control.plyr__tab-focus {
>   box-shadow: 0 0 0 5px rgba(YourRGBColor, .5);
> }
> 
> .plyr__menu__container .plyr__control[role=menuitemradio][aria-checked=true]::before {
>   background: YourColor;
> }
> ```
> 
> I hope I helped you!

Thanks ! Just add _plyr--audio_ to change audio stream color as well
```css
...
.plyr--audio .plyr__control.plyr__tab-focus,
.plyr--audio .plyr__control:hover,
.plyr--audio .plyr__control[aria-expanded=true] {
  background: YourColor;
}
...
```
