### ISSUE TITLE
How disable the hover shadow

### ISSUE THREAD

**Issue by HectorLS** [sampotts/plyr#721]
**### Environment**
- Browser: Chrome
- Operating System: OSX High Sierra
- "plyr": "^2.0.18",
**Players affected:**
- [ ] HTML5 Video
**### Steps to reproduce** 
- Hover a video

Hello, awesome library by the way
I added a video and looks great with this options

```javascript
var options = {
      controls: [],
      autoplay: true,
      fullscreen: {
        enabled: false
      }
   };
```

Looks nice, but then when i hover the video i got a kind of box-shadow at the bottom, how can i disable this.

The reason is that when i HOVER,  this class `plyr--hide-controls` disappear, so how can i force this class to stay on hover.

thanks in advance.

**Comment by HectorLS** [comment]
I just found the problem, just need to add this 😺 

```scss
.plyr--video {
     
          .plyr__controls {
            opacity: 0 !important;
          }
}
```

**Comment by friday** [comment]
You need the gradient in order to see the controls on white or very light backgrounds, or you'll get this:

![screen shot 2017-11-21 at 15 15 59](https://user-images.githubusercontent.com/515120/33077029-ed309dc2-cece-11e7-8941-c06f0c11410f.png)

Unless you know this won't happen, try to make the background lighter instead. Ex 
```css
.plyr--video .plyr__controls {
    background: linear-gradient(transparent, rgba(0, 0, 0, .15))
}
```
