### ISSUE TITLE
Forgotten variable in CSS

### ISSUE THREAD

**Issue by Antonio-Laguna** [sampotts/plyr#818]
### Expected behavior

Don't have undefined CSS variables.

### Actual behavior

There are undefined CSS Variables

### Steps to reproduce
- https://raw.githubusercontent.com/sampotts/plyr/master/dist/plyr.css

If you look there, you'll see this declaration: 

```css
::-webkit-slider-runnable-track{
  background:0 0;
  border:0;
  border-radius:3px;
  height:6px;
  transition:all .3s ease;
  -webkit-user-select:none;
  user-select:none;
  background-image:linear-gradient(to right,currentColor var(--value),transparent var(--value))
}
```

Which has the `--value` variable there. Comes from here https://github.com/sampotts/plyr/blob/600f0eb8a3cf49f5268e5c15487797d496bc19b6/src/sass/components/sliders.scss#L22

It does seem the only element having a var notation. Keen to submit a PR but unsure what the intended value was.
