### ISSUE TITLE
buttons in Framework7 (and possibly other frameworks)

### ISSUE THREAD

**Issue by jwjcmw** [sampotts/plyr#928]
Over in the vue-plyr issues, someone brought up that they were using Framework7, and the buttons were stretching out, which looks to be due to a global button style in the F7 css.  Would it make sense to add:
```css
button {
        font: inherit;
        line-height: inherit;
        width: inherit;  /*this is the added line*/
    }
```
to the plyr base.scss to make sure this isn't an issue?  I can generate a PR if so.
The issue with a screenshot is here: https://github.com/redxtech/vue-plyr/issues/15
